-- ============================================================
-- Supplier Registry Seed Data
-- ============================================================

SET IDENTITY_INSERT [purchase].[Supplier] ON;

INSERT INTO [purchase].[Supplier] (Id, BusinessId, Name, IsActive, CreatedAtUtc)
VALUES
(1, 1, 'Destination Fitness', 1, GETUTCDATE()),
(2, 1, 'Bazaraki', 1, GETUTCDATE()),
(3, 1, 'Nicosia Municipality', 1, GETUTCDATE()),
(4, 1, 'Parga', 1, GETUTCDATE()),
(5, 1, 'EKO', 1, GETUTCDATE()),
(6, 1, 'Voici La Mode LTD', 1, GETUTCDATE()),
(7, 1, 'ERA', 1, GETUTCDATE()),
(8, 1, 'Crestolex LTD (Local All Day)', 1, GETUTCDATE()),
(9, 1, 'Neocleous & Constantinides LTD (Babylon)', 1, GETUTCDATE()),
(10, 1, 'Mega Brands Outlet', 1, GETUTCDATE()),
(11, 1, 'To Kafe tis Crysanthis LTD', 1, GETUTCDATE()),
(12, 1, 'Mediterranean Home of Seafood LTD (Ocean Basket)', 1, GETUTCDATE()),
(13, 1, 'Lionello Investments LTD (Taerna Stou Rousia)', 1, GETUTCDATE()),
(14, 1, 'Glykolemon', 1, GETUTCDATE()),
(15, 1, 'Avantage B&R Italian Restaurants LTD (Jamie Oliver)', 1, GETUTCDATE()),
(16, 1, 'Super Home Center (DIY) Limited', 1, GETUTCDATE()),
(17, 1, 'Google Cloud EMEA Limited', 1, GETUTCDATE()),
(18, 1, 'WrpaMarket LLC', 1, GETUTCDATE()),
(19, 1, 'Canva Pty Limited', 1, GETUTCDATE()),
(20, 1, 'Eshop Cyprus LTD', 1, GETUTCDATE()),
(21, 1, 'MCIT LTD', 1, GETUTCDATE()),
(22, 1, 'Registry .CY', 1, GETUTCDATE()),
(23, 1, 'GoDaddy', 1, GETUTCDATE()),
(24, 1, 'Europlanet O.E.', 1, GETUTCDATE()),
(25, 1, 'The Fast Jap Co Ltd (Rebuke)', 1, GETUTCDATE()),
(26, 1, 'A.S. Twice As Nice Pastries Ltd', 1, GETUTCDATE()),
(27, 1, 'Bean Bar', 1, GETUTCDATE()),
(28, 1, 'Hetafre Trading Ltd', 1, GETUTCDATE()),
(29, 1, 'Mavros Ltd', 1, GETUTCDATE()),
(30, 1, 'Stop & Watch', 1, GETUTCDATE()),
(31, 1, 'Francium Enterprises (Celio)', 1, GETUTCDATE()),
(32, 1, 'LabelShop Dimatica s.r.l.', 1, GETUTCDATE()),
(33, 1, 'C.K.M. Microsat Internet Technology Ltd', 1, GETUTCDATE()),
(34, 1, 'C. Net Technologies Ltd', 1, GETUTCDATE()),
(35, 1, 'About You SE & Co. KG', 1, GETUTCDATE()),
(36, 1, 'A.M. EshopForFitness LTD', 1, GETUTCDATE()),
(37, 1, 'MindByte Communications LTD', 1, GETUTCDATE()),
(38, 1, 'AKVA', 1, GETUTCDATE()),
(39, 1, 'Cyta', 1, GETUTCDATE()),
(40, 1, 'Iminders', 1, GETUTCDATE()),
(41, 1, 'Database Mart', 1, GETUTCDATE()),
(42, 1, 'Envato Pty Ltd', 1, GETUTCDATE()),
(43, 1, 'University of Cyprus', 1, GETUTCDATE()),
(44, 1, 'Grammarlt Inc', 1, GETUTCDATE()),
(45, 1, 'L.S. Technipro Signs LTD', 1, GETUTCDATE()),
(46, 1, 'AHK', 1, GETUTCDATE()),
(47, 1, 'Cablenet', 1, GETUTCDATE()),
(48, 1, 'Carmaster LTD', 1, GETUTCDATE()),
(49, 1, 'W.P.E. Print Ltd', 1, GETUTCDATE()),
(50, 1, 'Chrismo Homeware LTD', 1, GETUTCDATE()),
(51, 1, 'Motoattack', 1, GETUTCDATE()),
(52, 1, 'A.Piastr Copies & Printing Services Ltd', 1, GETUTCDATE()),
(53, 1, 'SCB DIY Limited', 1, GETUTCDATE()),
(54, 1, 'Lidl', 1, GETUTCDATE()),
(55, 1, 'G.A.P. Akis Express LTD', 1, GETUTCDATE()),
(56, 1, 'Pop Life', 1, GETUTCDATE()),
(57, 1, 'Metro', 1, GETUTCDATE()),
(58, 1, 'Sklavenitis', 1, GETUTCDATE()),
(59, 1, 'Best Values Discount Store Kennedy', 1, GETUTCDATE()),
(60, 1, 'Waddah Flahaha Trading LTD', 1, GETUTCDATE()),
(61, 1, 'Periptero Armenias (L&A MERX LTD)', 1, GETUTCDATE()),
(62, 1, 'A Xorpas & Sons Ltd', 1, GETUTCDATE()),
(63, 1, 'S.M. Sportswear Market LTD (Intersport)', 1, GETUTCDATE()),
(64, 1, 'Moda Retrato LTD (Massimo Dutti)', 1, GETUTCDATE()),
(65, 1, 'S.T Karpos Zois LTD', 1, GETUTCDATE()),
(66, 1, 'Afelandra', 1, GETUTCDATE()),
(67, 1, 'Vassos Eliades LTD', 1, GETUTCDATE()),
(68, 1, 'Char.J.Philippides & Sons LTD', 1, GETUTCDATE()),
(69, 1, 'Mariancchi (Karvounonostimies)', 1, GETUTCDATE()),
(70, 1, 'SVL Souvlaki Lovers LTD', 1, GETUTCDATE()),
(71, 1, 'Freeze Panes LTD (Brothers Bar And Grill)', 1, GETUTCDATE()),
(72, 1, 'Baristro Tou Nikola LTD', 1, GETUTCDATE()),
(73, 1, 'P. Ignatiou LTD (Coffee Bar Yard Lefkara)', 1, GETUTCDATE()),
(74, 1, 'R.A.M. OIL Cyprus LTD', 1, GETUTCDATE()),
(75, 1, 'ESSO', 1, GETUTCDATE()),
(76, 1, 'Cafe La Mode', 1, GETUTCDATE()),
(77, 1, 'To Potopoleio L.A. Armenias LTD', 1, GETUTCDATE()),
(78, 1, 'Vienna Bakeries', 1, GETUTCDATE()),
(79, 1, 'Zorbas Bakeries', 1, GETUTCDATE()),
(80, 1, 'HM House Market (Cyprus) LTD', 1, GETUTCDATE()),
(81, 1, 'Clock Cafe Arise', 1, GETUTCDATE()),
(82, 1, 'New Division', 1, GETUTCDATE()),
(83, 1, 'ENI', 1, GETUTCDATE()),
(84, 1, 'Pantelis Katelaris (Pergamos)', 1, GETUTCDATE()),
(85, 1, 'Marks & Spencer', 1, GETUTCDATE()),
(86, 1, 'King of Toys', 1, GETUTCDATE()),
(87, 1, 'The Mall of Cyprus', 1, GETUTCDATE()),
(88, 1, 'Serenity', 1, GETUTCDATE()),
(89, 1, 'GEVOREST', 1, GETUTCDATE()),
(90, 1, 'Leroy Merlin', 1, GETUTCDATE()),
(91, 1, 'SPANIAS', 1, GETUTCDATE()),
(92, 1, 'Seagull Software', 1, GETUTCDATE()),
(93, 1, 'Piastr Design & Copy Center', 1, GETUTCDATE()),
(94, 1, 'Puplic', 1, GETUTCDATE()),
(95, 1, 'Ebay', 1, GETUTCDATE()),
(96, 1, 'Darya International Business GmbH', 1, GETUTCDATE()),
(97, 1, 'Web Supplies', 1, GETUTCDATE()),
(98, 1, 'AliExpress', 1, GETUTCDATE()),
(99, 1, 'OpenAI', 1, GETUTCDATE()),
(100, 1, 'DHL', 1, GETUTCDATE()),
(101, 1, 'Vallestino LTD', 1, GETUTCDATE()),
(102, 1, 'Foodhaus', 1, GETUTCDATE()),
(103, 1, 'CJS CD Keys', 1, GETUTCDATE()),
(104, 1, 'Syntechniako Farmakio LTD', 1, GETUTCDATE()),
(105, 1, 'LinkedIn Ireland Unlimited Company', 1, GETUTCDATE()),
(106, 1, 'AnyDesk Software GmbH', 1, GETUTCDATE()),
(107, 1, 'CJS & Services LTD', 1, GETUTCDATE()),
(108, 1, 'Ministry Of Interior', 1, GETUTCDATE()),
(109, 1, 'Registrar Of Companies And Intellectual Property', 1, GETUTCDATE()),
(110, 1, 'Tax And Postal Charges', 1, GETUTCDATE()),
(111, 1, 'EOA', 1, GETUTCDATE()),
(112, 1, 'Alphamega', 1, GETUTCDATE()),
(113, 1, 'Melis', 1, GETUTCDATE()),
(114, 1, 'G.Giagkou', 1, GETUTCDATE()),
(115, 1, 'Alexandros Stephanis & Co Ltd', 1, GETUTCDATE()),
(116, 1, 'AT Digital LTD', 1, GETUTCDATE()),
(117, 1, 'EASY USE Susanne Moehring', 1, GETUTCDATE()),
(118, 1, 'AGELO Sales LTD', 1, GETUTCDATE()),
(119, 1, 'Monza SA', 1, GETUTCDATE()),
(120, 1, 'Aegean', 1, GETUTCDATE()),
(121, 1, 'Daeya International Business GmbH', 1, GETUTCDATE()),
(122, 1, 'Finders Bar and Grill (Aga Andreou Ltd)', 1, GETUTCDATE()),
(123, 1, 'Grains & Greens', 1, GETUTCDATE()),
(124, 1, 'Treis & O Koukos', 1, GETUTCDATE()),
(125, 1, 'Ocean Basket Mall of Cyprus', 1, GETUTCDATE()),
(126, 1, 'DIMSTEF Creperie', 1, GETUTCDATE()),
(127, 1, 'MARZANO', 1, GETUTCDATE()),
(128, 1, 'Ocean Basket Dhekelia', 1, GETUTCDATE()),
(129, 1, 'KEM (Ovenit LTD)', 1, GETUTCDATE()),
(130, 1, 'Camel Active', 1, GETUTCDATE()),
(131, 1, 'A.S. Xinaris & Sons LTD', 1, GETUTCDATE()),
(132, 1, 'MANOLIS M. Key Services', 1, GETUTCDATE()),
(133, 1, 'Thunderwash (G & S Herodotou Brothers)', 1, GETUTCDATE()),
(134, 1, 'META', 1, GETUTCDATE()),
(135, 1, 'Andreas TH.CHILAS LTD', 1, GETUTCDATE()),
(136, 1, 'Petrolina', 1, GETUTCDATE()),
(137, 1, 'Pasta Strada', 1, GETUTCDATE()),
(138, 1, 'Oriental', 1, GETUTCDATE()),
(139, 1, 'Piatsa Gourounaki', 1, GETUTCDATE()),
(140, 1, 'Public', 1, GETUTCDATE()),
(141, 1, 'Rivergate Bibliopolis', 1, GETUTCDATE()),
(142, 1, 'KIRO', 1, GETUTCDATE()),
(143, 1, 'S&N Construction', 1, GETUTCDATE()),
(144, 1, 'E.N.A Humans The Agency Limited', 1, GETUTCDATE()),
(145, 1, 'Easy by Europlanet', 1, GETUTCDATE()),
(146, 1, 'Enterprise', 1, GETUTCDATE()),
(147, 1, 'Monzilla Foundation', 1, GETUTCDATE()),
(148, 1, 'Tmima Forologias', 1, GETUTCDATE()),
(149, 1, 'Dimos Lefkosias', 1, GETUTCDATE()),
(150, 1, 'EKO Larnakos', 1, GETUTCDATE()),
(151, 1, 'Two Guys BBQ', 1, GETUTCDATE()),
(152, 1, 'New York', 1, GETUTCDATE()),
(153, 1, 'Athienites', 1, GETUTCDATE()),
(154, 1, 'WT.Miami AGL Ltd', 1, GETUTCDATE()),
(155, 1, 'LabelShop', 1, GETUTCDATE()),
(156, 1, 'Microsat', 1, GETUTCDATE());

SET IDENTITY_INSERT [purchase].[Supplier] OFF;

-- ============================================================
-- Expense Category Registry Seed Data
-- ============================================================

SET IDENTITY_INSERT [purchase].[ExpenseCategory] ON;

INSERT INTO [purchase].[ExpenseCategory] (Id, BusinessId, Name, IsActive, CreatedAtUtc)
VALUES
(1, 1, 'Staff Gym', 1, GETUTCDATE()),
(2, 1, 'Office Furniture', 1, GETUTCDATE()),
(3, 1, 'Office Supplies/Stationery', 1, GETUTCDATE()),
(4, 1, 'Parking', 1, GETUTCDATE()),
(5, 1, 'Books', 1, GETUTCDATE()),
(6, 1, 'Fuels/Traveling Expenses', 1, GETUTCDATE()),
(7, 1, 'Business Meetings/Restaurants & Bar', 1, GETUTCDATE()),
(8, 1, 'Staff Outfit/Uniform', 1, GETUTCDATE()),
(9, 1, 'Software Subscriptions/Service Subscriptions', 1, GETUTCDATE()),
(10, 1, 'Hardware/PC Equipment', 1, GETUTCDATE()),
(11, 1, 'Domains', 1, GETUTCDATE()),
(12, 1, 'Travel/Suitcase', 1, GETUTCDATE()),
(13, 1, 'Gifts/Customer Gifts', 1, GETUTCDATE()),
(14, 1, 'Food/Supermarket', 1, GETUTCDATE()),
(15, 1, 'Shipping', 1, GETUTCDATE()),
(16, 1, 'Labels', 1, GETUTCDATE()),
(17, 1, 'Utilities (Electricity, Water)', 1, GETUTCDATE()),
(18, 1, 'Telephone/Internet Bills', 1, GETUTCDATE()),
(19, 1, 'Conferences/Training', 1, GETUTCDATE()),
(20, 1, 'Office Renovation', 1, GETUTCDATE()),
(21, 1, 'Printing', 1, GETUTCDATE()),
(22, 1, 'Vehicle Service/Transportation', 1, GETUTCDATE()),
(23, 1, 'Security', 1, GETUTCDATE()),
(24, 1, 'Government/Infringement', 1, GETUTCDATE()),
(25, 1, 'Health & Safety/Pharmacy', 1, GETUTCDATE()),
(26, 1, 'Advertising/Marketing', 1, GETUTCDATE()),
(27, 1, 'Car Rental', 1, GETUTCDATE()),
(28, 1, 'Kitchen/Bath Equipment', 1, GETUTCDATE()),
(29, 1, 'Maintenance', 1, GETUTCDATE()),
(30, 1, 'AI Software', 1, GETUTCDATE()),
(31, 1, 'Building Repair/Construction', 1, GETUTCDATE());

SET IDENTITY_INSERT [purchase].[ExpenseCategory] OFF;
